config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  resources 'users'
  resources 'posts'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true , uniqueness: true
  has_secure_password
end

app/controllers/application_controller.rb
# coding: utf-8
class ApplicationController < ActionController::Base
  include SessionsHelper

  protect_from_forgery with: :exception

  add_flash_types :success, :info, :warning, :danger
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(content: params[:content])
    if @post.save
      redirect_to posts_path, success: "登録完了"
    else
      redirect_to root_path, danger: "登録失敗"
    end

  end


end

app/controllers/sessions_controller.rb
# coding: utf-8
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.find_by(name: params[:name])
    if user && user.authenticate(params[:password])
      log_in user
      redirect_to root_path, success: "ログインに成功しました"

    else
      redirect_to login_path, danger: "ログインに失敗しました"
    end
  end

  def destroy
    log_out
    redirect_to root_path, success: "ログアウトしました"
  end
end

app/controllers/users_controller.rb
# coding: utf-8
class UsersController < ApplicationController
  before_action :authenticate_user, {only: [:show]}
  
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to root_path, success: "ようこそProChartへ"
    else
      redirect_to new_user_path, danger: "ユーザー名が重複しているか、書式を満たしていません"
    end
  end

  def show
    @user = User.find(params[:id])
  end
  
  private
  def user_params
    params.required(:user).permit(:name, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
# coding: utf-8
module SessionsHelper
    def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def authenticate_user
    if current_user == nil
      redirect_to root_path, danger: "のぞきはダメよ"
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<center>
&copy Kyutech Programming Club
</center>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-sm navbar-dark bg-dark mt-3 mb-3">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav4" aria-controls="navbarNav4" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="container">
    <%= link_to 'ProChart', root_path, class: 'navbar-brand' %>
    <div class="collapse navbar-collapse justify-content-end">
      <ul class="navbar-nav">
        <li class="nav-item">

        </li>
        <% if current_user.nil? %>
          <li class="nav-item">
            <%= link_to 'Login', login_path, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to current_user.name, user_path(id: current_user), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Logout', logout_path, method: :delete, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProChart</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name %>">
        <%= msg.html_safe %>
      </div>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>

   <%= render "layouts/footer" %>
  </body>
</html>

app/views/posts/index.html.erb
<h1>投稿</h1>
<%= link_to "新言語登録", new_post_path %>
<p>登録言語リスト</p>
<% @posts.each do |post| %>
  <%= post.content %>
<% end %>

app/views/posts/new.html.erb
<h1>投稿</h1>

<%= form_with url: posts_path do |f| %>
  <%= f.label :content %>
  <%= f.text_field :content %>
<%= f.submit "新規登録" %>

<% end %>

app/views/users/index.html.erb
<h1>TOP</h1>
<% if current_user %>
  <% @users.each do |user| %>
    <%= link_to user.name, user_path(user) %>
  <% end %>
  <%= link_to "投稿", new_post_path %>

<% else %>
  <%= link_to "ログイン", login_path %>
  <%= link_to "新規登録", new_user_path %>
<% end %>

app/views/users/new.html.erb
<h1>新規登録</h1>
<%= form_with model: @user do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :password%>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>